// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCBLLMjW3ODLRXFVBoAz0PkbnFvJYBWQ',
    appId: '1:293400102880:web:6953ae6a4dfeea7f440d85',
    messagingSenderId: '293400102880',
    projectId: 'geo-app-688c8',
    authDomain: 'geo-app-688c8.firebaseapp.com',
    storageBucket: 'geo-app-688c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv68TW41d0WwRv87poOJ7NQF6GfDtFp3E',
    appId: '1:293400102880:android:8dd3a395f1963d33440d85',
    messagingSenderId: '293400102880',
    projectId: 'geo-app-688c8',
    storageBucket: 'geo-app-688c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQze_TFJW_7o-Bq0cuRXbKMvG6m2dF_w',
    appId: '1:293400102880:ios:bbde77daffff0dcb440d85',
    messagingSenderId: '293400102880',
    projectId: 'geo-app-688c8',
    storageBucket: 'geo-app-688c8.appspot.com',
    iosBundleId: 'com.example.geoApp',
  );
}
